### ISSUE TITLE
Separate xray views

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-desktop-application#3]
The xray slice view and the xrayFeatures slice view are linked-- I guess they are the same underlying view. Need to separate them so that some objects can be visible in one view but not the other.

Currently not sure how to do this. Create an entirely new slice view object? Or are they already separate but just need to be unlinked?

Somewhat related: [This](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#set-all-slice-views-linked-by-default) gives a hint as to how we can unlink the _controls_, at least.

**Comment by ebrahimebrahim** [comment]
Hints for two potential approaches:

* Slicer.util implementation related to setSliceViewerLayers.: See https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Base/Python/slicer/util.py#L475
* Link behavior can be tweaked through “ViewGroup”. See https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Libs/MRML/Core/vtkMRMLAbstractViewNode.h#L72-L83

**Comment by ebrahimebrahim** [comment]
The goal is to get fine control over node visibility by view node, so that a node can be visible in one slice view and not in another. This needs to be done for volume nodes and for segmentation nodes.

Potential approaches moving forward:

For volume nodes, we have the following solution: get the `vtkMRMLSliceCompositeNode` associated to each `qMRMLSliceWidget`, and use `vtkMRMLSliceCompositeNode::SetBackgroundVolumeID` to set which volume node should be visible in that view. Thanks @sjh26 for pointing me in the right direction here!

For segmentation nodes we cannot take the same approach, because their display is not managed by a `vtkMRMLSliceCompositeNode`. Instead their display is managed by `vtkMRMLSegmentationsDisplayableManager2D`. I don't see a way to tell the display manager to just not display things, nor do I see a way to tell the view node to ditch a certain a displayable manager. But here is a hack that worked: set the displayable manager's scene to null:
```py
layoutManager = slicer.app.layoutManager()
sw = layoutManager.sliceWidget('xray')
sv = sw.sliceView()
dm = sv.displayableManagerByClassName("vtkMRMLSegmentationsDisplayableManager2D")
dm.SetMRMLScene(None) # surprisingly does not break things :)
```

Regarding the view groups approach: it seems the purpose of view groups is to organize which views get linked in the sense of zooming, panning, etc. As far as I can tell, view groups are not designed to allow for fine control of node visibility. Visible nodes are visible in all view groups.

**Comment by jcfr** [comment]
To follow up, after reading the description, visibility of segmentation can be configured as such from the UI:

![image](https://user-images.githubusercontent.com/219043/152228243-826d6f19-4a90-4d92-84c3-70fa74380a31.png)

Or programmatically using `AddViewNodeID(), ViewNodeIDs, RemoveViewNodeID(), RemoveAllViewNodeIDs()` from `vtkMRMLDisplayNode`.
See https://apidocs.slicer.org/master/classvtkMRMLDisplayNode.html#a62cff2549fe8c0c4fbff5b363031e242

**Comment by ebrahimebrahim** [comment]
> Or programmatically using `AddViewNodeID(), ViewNodeIDs, RemoveViewNodeID(), RemoveAllViewNodeIDs()` from `vtkMRMLDisplayNode`.

Aha, this is what I've been looking for! Thank you!
