### ISSUE TITLE
Building successful but python modules not being found

### ISSUE THREAD

**Issue by ebrahimebrahim** [KitwareMedical/lungair-desktop-application#39]
> I am building the LungAIRApp-real file but, when I run it, various things that it is supposed to be finding aren't found.  That is, the app launches and shows a traditional 3D Slicer layout but all (or at least much) of the lung-air functionality is missing.  Especially if you know off the top of your head, I could use help with which of the following are supposed to be built with the LungAIRApp and which are supposed to be installed on my system already?  Or if you have any other leads, like environment variables that I need to set or not set?!

> I have Qt 5.15.2 and am building with `-DQt5_DIR:PATH="$HOME"/Support/Qt/5.15.2/gcc_64/lib/cmake/Qt5` to the point of getting an app that runs (without lung air functionality), so I am especially perplexed that qt cannot be found.

> I am using Ubuntu 20.04 and Python 3.8.10.

```txt
"ModuleNotFoundError: No module named" for ctk, qt, SegmentEditorEffects, slicer, SubjectHierarchyPlugins, torch, and vtk.

"Fail to instantiate module" for AddManyMarkupsFiducialTest, ColorLegendSelfTest, CropVolumeSequence, DICOM, DICOMEnhancedUSVolumePlugin, DICOMGeAbusPlugin, DICOMImageSequencePlugin, DICOMPatcher, DICOMScalarVolumePlugin, DICOMSlicerDataBundlePlugin, DICOMVolumeSequencePlugin, Home, MarkupsInCompareViewersSelfTest, MarkupsInViewsSelfTest, NeurosurgicalPlanningTutorialMarkupsSelfTest, PluggableMarkupsSelfTest, ScreenCapture, SegmentEditor, SegmentStatistics, and SelfTests.
```

**Comment by ebrahimebrahim** [comment]
Let me try doing a clean build and see if I can reproduce the error.

There's only one environment variable that I set while building: adding my custom path to `qt-everywhere-build-5.15.1/lib` into my `LD_LIBRARY_PATH`. That doesn't seem to be the issue here though, since you are building just fine and what ends up not being found is on the python end.

When you run the application is it possible for you to get into a python console?

When I go into my python console and
```py
import ctk
print(ctk.__file__)
```
I get `'/home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/Python/ctk/__init__.py'`.

Does your superbuild directory have, for example, a successfully built `CTK-build/CTK-build/bin/Python` ?

**Comment by Leengit** [comment]
Thank you @ebrahimebrahim for creating this issue and the help.  If I go into the Python Interactor, via ctrl-3 from LungAIR, and type `import ctk` then I get `No module named 'ctk'`.  I do have the file `lungair-SuperBuild-Debug-Qt5.15.2/CTK-build/CTK-build/bin/Python/ctk/__init__.py` for what it is worth.

It feels like a missing environment variable (or part) to me, such as a missing entry in my `LD_LIBRARY_PATH` or the corresponding thing for Python.

If not that ... I have a fear that the problem is related to the fact that I recently upgraded my system to use Python 3.8 as the default, via `sudo update-alternatives` because I also have additional Python versions installed.  Now that 3.8 is the default, perhaps I need to `apt reinstall` several packages so that 3.8 can find them.

**Comment by ebrahimebrahim** [comment]
Slicer should pull in and build its own python. In the superbuild directory there should be a directory with a name like `Python-3.9.10` which contains the python source code that will be compiled during the build process. This makes me think that your system Python can't cause problems... but I'm not confident in saying that.

Hmmm we can try using `ldd` to see where the executable is trying to look for the libraries it linked to.

When `cd` into the superbuild directory and then run
```bash
ldd Slicer-build/bin/LungAIRApp-real  | grep python
```
I get
```txt
libpython3.9.so => /home/ebrahim/LungAIR-SuperBuild/python-install/lib/libpython3.9.so (0x00007effe3084000)
```
Here is another one we might look at:
```bash
ldd Slicer-build/bin/LungAIRApp-real  | grep CTK
```
gives me
```txt
	libCTKVisualizationVTKWidgets.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKVisualizationVTKWidgets.so.0.1 (0x00007f4d630ae000)
	libCTKScriptingPythonWidgets.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKScriptingPythonWidgets.so.0.1 (0x00007f4d63094000)
	libCTKDICOMWidgets.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKDICOMWidgets.so.0.1 (0x00007f4d62fcf000)
	libCTKWidgets.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKWidgets.so.0.1 (0x00007f4d62d50000)
	libCTKImageProcessingITKCore.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKImageProcessingITKCore.so.0.1 (0x00007f4d5a9b8000)
	libCTKVisualizationVTKCore.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKVisualizationVTKCore.so.0.1 (0x00007f4d5a961000)
	libCTKDICOMCore.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKDICOMCore.so.0.1 (0x00007f4d5a8a0000)
	libCTKScriptingPythonCore.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKScriptingPythonCore.so.0.1 (0x00007f4d5a826000)
	libCTKCore.so.0.1 => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CTK-build/bin/libCTKCore.so.0.1 (0x00007f4d5a75d000)
	libPythonQt.so => /home/ebrahim/LungAIR-SuperBuild/CTK-build/CMakeExternals/Install/lib/libPythonQt.so (0x00007f4d58aef000)

```

**Comment by ebrahimebrahim** [comment]
@Leengit Try now (without the symbolic link).

On first run you should get an error saying that monai is not found, then you can use the button to install monai and restart the application. Then it should work. Note that it will freeze up for a while during the large torch download. Let me know how it goes!

**Comment by Leengit** [comment]
Yes, very good, it now launches, warned me about missing MONAI, and gave me a nice button in the Advanced section to check for and install MONAI.  I also installed ITK-python, pandas, and matplotlib.

Perhaps unrelated and perhaps merely an ignorable warning but, just in case ... upon relaunch the console is saying
```text
Warning: Found an unexpected qMRMLPlotWidget named "qMRMLPlotWidget"; there may be UI setup issues.
```

**Comment by ebrahimebrahim** [comment]
Great! Yes, that warning is ignorable.... I need to fix an assumption I was
making about Slicer's creation and naming of qMRMLPlotWidgets on launch.

Best,
Ebrahim
